import "./globals.css";
import { Inter } from "next/font/google";
import LayoutProvider from "@/components/layoutProvider/LayoutProvider";
import { Toaster } from "react-hot-toast";



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster />
          <LayoutProvider>
            {children}
          </LayoutProvider>
      </body>
    </html>
  );
}
